### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by garrettlangley** [oursiberia/cordova-plugin-visit#2]
Any chance you could provide some documentation?

Expected behavior onVisit?

**Comment by ChristopherJoonMiller** [comment]
I've provided some basic documentation on how to use this plugin. Please comment if you feel like what is provided is sufficient and I will close this issue... or ask for additional details. Thanks!

**Comment by garrettlangley** [comment]
@ChristopherJoonMiller this looks really helpful! one question -> how do you recommend testing? possible in the simulator?

thanks,
garrett

**Comment by fsegouin** [comment]
@garrettlangley Unfortunately I've never got a CLVisit triggered in the simulator. There is currently no way of testing this feature other than taking your iPhone for a walk.

**Comment by ChristopherJoonMiller** [comment]
I was able to get it to trigger using xcode debug location... It' s just not a reliable thing. It's whenever apple decides you visited something.

**Comment by garrettlangley** [comment]
thanks guys, very helpful

integrating now and will let you know if other questions come up
